
version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    # env_file: .env
    environment:
    - ES_URL=http://es:9002
    command: cargo run -- examples/honeypot.toml
    depends_on:
      - es
    # volumes:
    #   - ./:/app
  es:
    image: cloudunit/elasticsearch-2.4
    ports:
      - "9002:9002"
